export const Interests = [
  "Football",
  "Basketball",
  "Baseball",
  "Soccer",
  "Tennis",
  "Golf",
  "Sports",
  "Music",
  "Movies",
  "Books",
  "Art",
  "Dance",
  "Food",
  "Travel",
  "Fashion",
  "Fitness",
  "Health",
  "Tech",
  "Science",
  "Politics",
  "Business",
  "Education",
  "History",
  "Languages",
  "Culture",
  "Lifestyle",
  "Gaming",
  "Entertainment",
  "Social",
  "Environment",
  "Tattoos",
  "Pets",
  "Cars",
  "Motorcycles",
  "Planes",
  "Boats",
  "School",
  // Creative & Arts
  "Photography",
  "Writing",
  "Poetry",
  "Drawing",
  "Painting",
  "Sculpture",
  "Crafts",
  "DIY",
  "Design",
  "Architecture",
  "Theater",
  "Comedy",
  "Singing",
  "Instruments",
  "Podcasts",
  // Outdoor & Adventure
  "Hiking",
  "Camping",
  "Rock Climbing",
  "Skiing",
  "Snowboarding",
  "Surfing",
  "Swimming",
  "Running",
  "Cycling",
  "Mountain Biking",
  "Fishing",
  "Hunting",
  "Kayaking",
  "Sailing",
  "Backpacking",
  "Nature",
  "Gardening",
  // Food & Drink
  "Cooking",
  "Baking",
  "Wine",
  "Coffee",
  "Tea",
  "Cocktails",
  "Beer",
  "Restaurants",
  "Vegetarian",
  "Vegan",
  // Wellness & Spirituality
  "Yoga",
  "Meditation",
  "Mindfulness",
  "Spirituality",
  "Mental Health",
  "Self Care",
  "Therapy",
  "Wellness",
  // Hobbies & Collections
  "Board Games",
  "Card Games",
  "Chess",
  "Puzzles",
  "Collecting",
  "Antiques",
  "Vintage",
  "Comics",
  "Anime",
  "Manga",
  "Cosplay",
  // Social & Relationships
  "Dating",
  "Relationships",
  "Family",
  "Friends",
  "Community",
  "Volunteering",
  "Charity",
  "Activism",
  "Human Rights",
  // Professional & Learning
  "Entrepreneurship",
  "Investing",
  "Real Estate",
  "Marketing",
  "Psychology",
  "Philosophy",
  "Astronomy",
  "Geography",
  "Mathematics",
  "Engineering",
  "Medicine",
  "Law",
  // Entertainment & Media
  "TV Shows",
  "Netflix",
  "YouTube",
  "TikTok",
  "Social Media",
  "Streaming",
  "Concerts",
  "Festivals",
  "Live Music",
  "Clubbing",
  "Nightlife",
  // Lifestyle & Personal
  "Minimalism",
  "Sustainability",
  "Eco Friendly",
  "Zero Waste",
  "Thrifting",
  "Shopping",
  "Beauty",
  "Skincare",
  "Makeup",
  "Hair",
  "Jewelry",
  "Piercings",
  // Sports & Activities
  "Volleyball",
  "Hockey",
  "Martial Arts",
  "Boxing",
  "Wrestling",
  "Gymnastics",
  "Track and Field",
  "CrossFit",
  "Pilates",
  "Dancing",
  "Ballroom",
  "Salsa",
  "Hip Hop",
  "Ballet",
  // Travel & Culture
  "Road Trips",
  "Backpacking",
  "International Travel",
  "Local Exploration",
  "Museums",
  "Festivals",
  "Cultural Events",
  "Languages Learning",
  "Study Abroad",
  // Technology & Innovation
  "Programming",
  "Web Development",
  "App Development",
  "AI",
  "Crypto",
  "Blockchain",
  "Startups",
  "Innovation",
  "Gadgets",
  "VR",
  "AR",
  // Quirky & Unique
  "Astrology",
  "Tarot",
  "Crystals",
  "Conspiracy Theories",
  "True Crime",
  "Horror",
  "Paranormal",
  "UFOs",
  "Magic",
  "Escape Rooms",
  "Trivia",
  "Karaoke",
  "Open Mic",
  "Stand Up Comedy",
];
