export default function Privacy() {
  return (
    <div className="prose prose-invert">
      <h1>Privacy Policy</h1>
      <p>Last updated: July 2&#44; 2024</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection&#44; use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service&#44; You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <p>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>Affiliate</strong> means an entity that controls&#44; is
            controlled by or is under common control with a party&#44; where
            &quot;control&quot; means ownership of 50% or more of the
            shares&#44; equity interest or other securities entitled to vote for
            election of directors or other managing authority.
          </p>
        </li>
        <li>
          <p>
            <strong>Application</strong> refers to 2 Man&#44; the software
            program provided by the Company.
          </p>
        </li>
        <li>
          <p>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;&#44; &quot;We&quot;&#44; &quot;Us&quot; or
            &quot;Our&quot; in this Agreement) refers to 2 Man.
          </p>
        </li>
        <li>
          <p>
            <strong>Country</strong> refers to: California&#44; United States
          </p>
        </li>
        <li>
          <p>
            <strong>Device</strong> means any device that can access the Service
            such as a computer&#44; a cellphone or a digital tablet.
          </p>
        </li>
        <li>
          <p>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </p>
        </li>
        <li>
          <p>
            <strong>Service</strong> refers to the Application.
          </p>
        </li>
        <li>
          <p>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service&#44; to provide the Service on behalf of the
            Company&#44; to perform services related to the Service or to assist
            the Company in analyzing how the Service is used.
          </p>
        </li>
        <li>
          <p>
            <strong>Usage Data</strong> refers to data collected
            automatically&#44; either generated by the use of the Service or
            from the Service infrastructure itself (for example&#44; the
            duration of a page visit).
          </p>
        </li>
        <li>
          <p>
            <strong>You</strong> means the individual accessing or using the
            Service&#44; or the company&#44; or other legal entity on behalf of
            which such individual is accessing or using the Service&#44; as
            applicable.
          </p>
        </li>
      </ul>
      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service&#44; We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include&#44; but
        is not limited to:
      </p>
      <ul>
        <li>
          <p>Email address</p>
        </li>
        <li>
          <p>First name and last name</p>
        </li>
        <li>
          <p>Address&#44; State&#44; Province&#44; ZIP/Postal code&#44; City</p>
        </li>
        <li>
          <p>Usage Data</p>
        </li>
      </ul>
      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address)&#44; browser type&#44; browser
        version&#44; the pages of our Service that You visit&#44; the time and
        date of Your visit&#44; the time spent on those pages&#44; unique device
        identifiers and other diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device&#44; We may
        collect certain information automatically&#44; including&#44; but not
        limited to&#44; the type of mobile device You use&#44; Your mobile
        device unique ID&#44; the IP address of Your mobile device&#44; Your
        mobile operating system&#44; the type of mobile Internet browser You
        use&#44; unique device identifiers and other diagnostic data.
      </p>
      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <h4>Information Collected while Using the Application</h4>
      <p>
        While using Our Application&#44; in order to provide features of Our
        Application&#44; We may collect&#44; with Your prior permission:
      </p>
      <ul>
        <li>
          <p>Information regarding your location</p>
        </li>
        <li>
          <p>
            Pictures and other information from your Device&apos;s camera and
            photo library
          </p>
        </li>
      </ul>
      <p>
        We use this information to provide features of Our Service&#44; to
        improve and customize Our Service. The information may be uploaded to
        the Company&apos;s servers and/or a Service Provider&apos;s server or it
        may be simply stored on Your device.
      </p>
      <p>
        You can enable or disable access to this information at any time&#44;
        through Your Device settings.
      </p>
      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li>
          <p>
            <strong>To provide and maintain our Service</strong>&#44; including
            to monitor the usage of our Service.
          </p>
        </li>
        <li>
          <p>
            <strong>To manage Your Account:</strong> to manage Your registration
            as a user of the Service. The Personal Data You provide can give You
            access to different functionalities of the Service that are
            available to You as a registered user.
          </p>
        </li>
        <li>
          <p>
            <strong>For the performance of a contract:</strong> the
            development&#44; compliance and undertaking of the purchase contract
            for the products&#44; items or services You have purchased or of any
            other contract with Us through the Service.
          </p>
        </li>
        <li>
          <p>
            <strong>To contact You:</strong> To contact You by email&#44;
            telephone calls&#44; SMS&#44; or other equivalent forms of
            electronic communication&#44; such as a mobile application&apos;s
            push notifications regarding updates or informative communications
            related to the functionalities&#44; products or contracted
            services&#44; including the security updates&#44; when necessary or
            reasonable for their implementation.
          </p>
        </li>
        <li>
          <p>
            <strong>To provide You</strong> with news&#44; special offers and
            general information about other goods&#44; services and events which
            we offer that are similar to those that you have already purchased
            or enquired about unless You have opted not to receive such
            information.
          </p>
        </li>
        <li>
          <p>
            <strong>To manage Your requests:</strong> To attend and manage Your
            requests to Us.
          </p>
        </li>
        <li>
          <p>
            <strong>For business transfers:</strong> We may use Your information
            to evaluate or conduct a merger&#44; divestiture&#44;
            restructuring&#44; reorganization&#44; dissolution&#44; or other
            sale or transfer of some or all of Our assets&#44; whether as a
            going concern or as part of bankruptcy&#44; liquidation&#44; or
            similar proceeding&#44; in which Personal Data held by Us about our
            Service users is among the assets transferred.
          </p>
        </li>
        <li>
          <p>
            <strong>For other purposes</strong>: We may use Your information for
            other purposes&#44; such as data analysis&#44; identifying usage
            trends&#44; determining the effectiveness of our promotional
            campaigns and to evaluate and improve our Service&#44; products&#44;
            services&#44; marketing and your experience.
          </p>
        </li>
      </ul>
      <p>We may share Your personal information in the following situations:</p>
      <ul>
        <li>
          <strong>With Service Providers:</strong> We may share Your personal
          information with Service Providers to monitor and analyze the use of
          our Service&#44; to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> We may share or transfer Your
          personal information in connection with&#44; or during negotiations
          of&#44; any merger&#44; sale of Company assets&#44; financing&#44; or
          acquisition of all or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your information with
          Our affiliates&#44; in which case we will require those affiliates to
          honor this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries&#44; joint venture partners or other companies
          that We control or that are under common control with Us.
        </li>
        <li>
          <strong>With business partners:</strong> We may share Your information
          with Our business partners to offer You certain products&#44; services
          or promotions.
        </li>
        <li>
          <strong>With other users:</strong> when You share personal information
          or otherwise interact in the public areas with other users&#44; such
          information may be viewed by all users and may be publicly distributed
          outside.
        </li>
        <li>
          <strong>With Your consent</strong>: We may disclose Your personal
          information for any other purpose with Your consent.
        </li>
      </ul>
      <h3>Retention of Your Personal Data</h3>
      <p>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example&#44; if we are required to retain
        your data to comply with applicable laws)&#44; resolve disputes&#44; and
        enforce our legal agreements and policies.
      </p>
      <p>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time&#44;
        except when this data is used to strengthen the security or to improve
        the functionality of Our Service&#44; or We are legally obligated to
        retain this data for longer time periods.
      </p>
      <h3>Transfer of Your Personal Data</h3>
      <p>
        Your information&#44; including Personal Data&#44; is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. It means that this
        information may be transferred to — and maintained on — computers
        located outside of Your state&#44; province&#44; country or other
        governmental jurisdiction where the data protection laws may differ than
        those from Your jurisdiction.
      </p>
      <p>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>
      <p>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </p>
      <h3>Delete Your Personal Data</h3>
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </p>
      <p>
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </p>
      <p>
        You may update&#44; amend&#44; or delete Your information at any time by
        signing in to Your Account&#44; if you have one&#44; and visiting the
        account settings section that allows you to manage Your personal
        information. You may also contact Us to request access to&#44;
        correct&#44; or delete any personal information that You have provided
        to Us.
      </p>
      <p>
        Please note&#44; however&#44; that We may need to retain certain
        information when we have a legal obligation or lawful basis to do so.
      </p>
      <h3>Disclosure of Your Personal Data</h3>
      <h4>Business Transactions</h4>
      <p>
        If the Company is involved in a merger&#44; acquisition or asset
        sale&#44; Your Personal Data may be transferred. We will provide notice
        before Your Personal Data is transferred and becomes subject to a
        different Privacy Policy.
      </p>
      <h4>Law enforcement</h4>
      <p>
        Under certain circumstances&#44; the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
      <h4>Other legal requirements</h4>
      <p>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>
      <h3>Security of Your Personal Data</h3>
      <p>
        The security of Your Personal Data is important to Us&#44; but remember
        that no method of transmission over the Internet&#44; or method of
        electronic storage is 100% secure. While We strive to use commercially
        acceptable means to protect Your Personal Data&#44; We cannot guarantee
        its absolute security.
      </p>
      <h2>Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data&#44; please contact Us. If
        We become aware that We have collected Personal Data from anyone under
        the age of 13 without verification of parental consent&#44; We take
        steps to remove that information from Our servers.
      </p>
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent&#44; We may
        require Your parent&apos;s consent before We collect and use that
        information.
      </p>
      <h2>Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link&#44; You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </p>
      <p>
        We have no control over and assume no responsibility for the
        content&#44; privacy policies or practices of any third party sites or
        services.
      </p>
      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let You know via email and/or a prominent notice on Our
        Service&#44; prior to the change becoming effective and update the
        &quot;Last updated&quot; date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy&#44; You can contact
        us:
      </p>
      <ul>
        <li>By email: support@twoman.dating</li>
      </ul>
    </div>
  );
}
