name: "deploy"

on:
  push:
    branches:
      - main
    paths:
      - 'twoman-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH and Deploy
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H api.twoman.dating >> ~/.ssh/known_hosts
          
          # Deploy only the API subdirectory using git subtree
          git subtree push --prefix=twoman-api ssh://dokku@api.twoman.dating/api.twoman.dating main --force || \
          git push ssh://dokku@api.twoman.dating/api.twoman.dating `git subtree split --prefix=twoman-api main`:main --force